spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: earliest
            group-id: my-group
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
